version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - redis_typescript_backend_toolkit:/data

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_typescript_backend_toolkit:/var/lib/postgresql/data

volumes:
  mongodb_typescript_backend_toolkit:
  redis_typescript_backend_toolkit:
  postgres_typescript_backend_toolkit:
